config/routes.rb
Rails.application.routes.draw do
  root to:'home#index'

  resources :genres, only: [:index, :show, :new, :create, :edit, :update]

  resources :directors, only: [:index, :show, :new, :create, :edit, :update]

  resources :movies, only: [:index, :show, :new, :create, :edit, :update] do
    patch(:release, on: :member)
    patch(:publish, on: :member)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/director.rb
class Director < ApplicationRecord
  belongs_to :favorite_genre, class_name: 'Genre'
  has_many :movies
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :directors, foreign_key: :favorite_genre_id
  has_many :movies
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :director
  belongs_to :genre
  enum(release_status: {
    unreleased: 0,
    released: 1
  })
  enum(publish_status: {
    draft: 0,
    published: 1
  })
  has_one_attached :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/directors_controller.rb
class DirectorsController < ApplicationController
  def index
    @directors = Director.all
  end

  def show
    @director = Director.find(params[:id])
    @movies = Movie.where(director_id: params[:id])
  end

  def new
    @director = Director.new
  end

  def create
    @director = Director.new(
      params.require(:director).permit(:name, :nationality, :birth_date, :favorite_genre_id)
    )

    if @director.save
      flash[:notice] = 'Director successfully created!'
      return redirect_to new_director_path
    end

    flash[:alert] = 'There was an error when trying to create the director.'
    render :new
  end

  def edit
    @director = Director.find(params[:id])
  end

  def update
    @director = Director.find(params[:id])

    year = params[:director]["birth_date(1i)"].to_i
    month = params[:director]["birth_date(2i)"].to_i
    day = params[:director]["birth_date(3i)"].to_i

    birth_date = Date.new(year, month, day)

    if @director.update(
      params.require(:director).permit(:name, :nationality, :birth_date, :favorite_genre_id)
    )
      flash[:notice] = 'Director successfully updated!'
      return redirect_to director_path
    end

    flash[:alert] = 'There was an error when trying to update the director.'
    render :edit
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def index
    @genres = Genre.all
  end
  def show
    @genre = Genre.find(params[:id])
    @movies = Movie.where(genre_id: params[:id])
  end

  def new
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(
      params.require(:genre).permit(:name)
    )
    if @genre.save
      flash[:notice] = 'Genre successfully created!'
      return redirect_to new_genre_path
    end

    flash[:alert] = 'There was an error when trying to create the genre.'
    render :new
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])

    if @genre.update(
      params.require(:genre).permit(:name)
    )
      flash[:notice] = 'Genre successfully updated!'
      return redirect_to(genre_path)
    end

    flash[:alert] = 'There was an error when trying to update the genre.'
    render :edit
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.published
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(
      params.require(:movie).permit(:title, :release_year, :synopsis, :country_of_origin, :duration_in_minutes, :director_id, :genre_id)
    )

    if @movie.save
      flash[:notice] = 'Movie successfully created!'
      return redirect_to new_movie_path
    end

    flash[:alert] = 'There was an error when trying to create the movie'
    render :new
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:id])

    if @movie.update(
      params.require(:movie).permit(:title, :release_year, :synopsis, :country_of_origin, :duration_in_minutes, :director_id, :genre_id)
    )
      if params[:movie][:image].present?
        @movie.image.attach(params[:movie][:image])
      end
      flash[:notice] = 'Movie successfully updated!'
      return redirect_to(movie_path)
    end

    flash[:alert] = 'There was an error when trying to update the movie.'
    render :edit
  end

  def release
    @movie = Movie.find(params[:id])
    if @movie.released?
      @movie.unreleased!
    else
      @movie.released!
    end

    if @movie.save
      flash[:notice] = 'Release status successfully set!'
      return redirect_to movie_path(@movie.id)
    end

    flash[:alert] = 'There was a problem when trying to set the release status.'
    redirect_to movie_path(@movie.id)
  end

  def publish
    @movie = Movie.find(params[:id])
    if @movie.published?
      @movie.draft!
    else
      @movie.published!
    end

    if @movie.save
      flash[:notice] = "Publish status successfully set!"
      return redirect_to movie_path(@movie.id)
    end

    flash[:alert] = "There was a problem when trying to set the publish status."
    redirect_to movie_path(@movie.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/directors/_form.html.erb
<%= link_to 'Back', directors_path %>

<% if flash[:notice] %>
  <div style="margin: 10px 0">
    <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:alert] %>
  <div style="margin: 10px 0">
    <%= flash[:alert] %>
  </div>
<% end %>

<%= form_with model: @director do |f| %>
  <div>
    <%= f.label :name, 'Name' %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :nationality, 'Nationality' %>
    <%= f.text_field :nationality %>
  </div>

  <div>
    <%= f.label :birth_date, 'Birth Date' %>
    <%= f.date_select :birth_date, start_year: 1900 %>
  </div>

  <div>
    <%= f.label :favorite_genre_id, 'Favorite Genre' %>
    <%= f.collection_select :favorite_genre_id, Genre.all, :id, :name %>
  </div>

  <div>
    <%= f.submit 'Save' %>
  </div>
<% end %>

app/views/directors/edit.html.erb
<h1>Edit Director</h1>

<%= render partial: 'form', locals: {director: @director} %>

app/views/directors/index.html.erb
<h1>Directors</h1>

<%= link_to 'Add', new_director_path %>
<%= link_to 'Back', :root %>

<dl>
  <% @directors.each do |director| %>
    <dt>
      <%= link_to(director.name, director_path(director)) %>
    </dt>
  <% end %>
</dl>

app/views/directors/new.html.erb
<h1>Register Director</h1>

<%= render partial: 'form', locals: {director: @director } %>

app/views/directors/show.html.erb
<h1>Director: <%= @director.name %></h1>

<%= link_to 'Add', new_director_path %>
<%= link_to 'Edit', edit_director_path %>
<%= link_to 'Back', directors_path %>

<dl>
  <dt>
    <strong>Name: </strong>
    <%= @director.name %>
  </dt>

  <dt>
    <strong>Nationality: </strong>
    <%= @director.nationality %>
  </dt>

  <dt>
    <strong>Birth Date: </strong>
    <%= @director.birth_date %>
  </dt>

  <dt>
    <strong>Favorite Genre: </strong>
    <%= @director.favorite_genre.name %>
  </dt>
</dl>

<dl>
  <dt>
    <strong>Directed Movies:</strong>
  </dt>
  <% @movies.each do |movie| %>
    <dt>
      <%= link_to movie.title, movie_path %>
    </dt>
  <% end %>
</dl>

app/views/genres/_form.html.erb
<%= link_to 'Back', genres_path %>

<% if flash[:notice] %>
  <div style="margin: 10px 0">
    <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:alert] %>
  <div style="margin: 10px 0">
    <%= flash[:alert] %>
  </div>
<% end %>

<%= form_with model: @genre do |f| %>
  <div>
    <%= f.label :name, 'Name' %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.submit 'Save' %>
  </div>
<% end %>

app/views/genres/edit.html.erb
<h1>Edit Genre</h1>

<%= render partial: 'form', locals: { genre: @genre } %>

app/views/genres/index.html.erb
<h1>Movie Genres</h1>

<%= link_to 'Back', :root %>
<%= link_to 'Add', new_genre_path %>

<dl>
  <% @genres.each do |genre| %>
    <dt>
      <%= link_to genre.name, genre_path(genre) %>
    </dt>
  <% end %>
</dl>

app/views/genres/new.html.erb
<h1>Register Genre</h1>

<%= render partial: 'form', locals: { genre: @genre } %>

app/views/genres/show.html.erb
<h1>Genre: <%= @genre.name %></h1>

<%= link_to 'Add', new_genre_path %>
<%= link_to 'Edit', edit_genre_path %>
<%= link_to 'Back', genres_path %>

<dl>
  <dt>
    <strong>Name: </strong>
    <%= @genre.name %>
  </dt>
</dl>
<dl>
  <dt>
    <strong>Movies in the Genre:</strong>
  </dt>
  <% @movies.each do |movie| %>
    <dt>
      <%= link_to movie.title, movie_path %>
    </dt>
  <% end %>
</dl>

app/views/home/index.html.erb
<h1>Movies Catalogue</h1>
<dl>
  <dt>
    <strong><%= link_to "Movies Index", movies_path %></strong>
  </dt>
  <dt>
    <strong><%= link_to "Directors Index", directors_path %></strong>
  </dt>
  <dt>
    <strong><%= link_to "Genres Index", genres_path %></strong>
  </dt>
</dl>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MoviesCatalogue</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movies/_form.html.erb
<%= link_to 'Back', movies_path %>

<% if flash[:notice] %>
  <div style="margin 10px 0">
    <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:alert] %>
  <div style="margin: 10px 0">
    <%= flash[:alert] %>
  </div>
<% end %>

<%= form_with model: @movie do |f| %>
  <div>
    <%= f.label :title, 'Title' %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :release_year, 'Release Year' %>
    <%= f.number_field :release_year %>
  </div>

  <div>
    <%= f.label :synopsis, 'Synopsis' %>
    <%= f.text_area :synopsis %>
  </div>

  <div>
    <%= f.label :country_of_origin, 'Country of Origin' %>
    <%= f.text_field :country_of_origin %>
  </div>

  <div>
    <%= f.label :duration_in_minutes, 'Duration in Minutes' %>
    <%= f.number_field :duration_in_minutes %>
  </div>

  <div>
    <%= f.label :director_id, 'Director' %>
    <%= f.collection_select :director_id, Director.all, :id, :name %>
  </div>

  <div>
    <%= f.label :genre_id, 'Genre' %>
    <%= f.collection_select :genre_id, Genre.all, :id, :name %>
  </div>

  <div>
    <%= f.file_field :image %>
  </div>

  <div>
    <%= f.submit 'Save' %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Edit Movie</h1>

<%= render partial: 'form', locals: {
  movie: @movie
} %>

app/views/movies/index.html.erb
<h1>Movies</h1>

<%= link_to 'Back', :root %>
<%= link_to 'Add', new_movie_path %>

<dl>
  <% @movies.each do |movie| %>
  <dt>
    <%= link_to "#{movie.title} (#{movie.release_year}) - #{movie.released? ? 'Released' : 'Unreleased'}", movie_path(movie) %>
  </dt>
  <dt>
  </dt>
  <% end %>
</dl>

app/views/movies/new.html.erb
<h1>Register Movie</h1>

<%= render partial: 'form', locals: {
  movie: @movie
} %>

app/views/movies/show.html.erb
<h1>Movie: <%= @movie.title %></h1>

<%= link_to 'Edit', edit_movie_path %>
<%= link_to 'Back', movies_path %>

<dl>
  <dt>
    <%= image_tag(@movie.image) if @movie.image.attached? %>
  </dt>
  <dt>
    <strong>Title: </strong>
    <%= @movie.title %>
  </dt>

  <dt>
    <strong>Release Year: </strong>
    <%= @movie.release_year %>
  </dt>
  
  <dt>
    <strong>Synopsis: </strong>
    <%= @movie.synopsis %>
  </dt>

  <dt>
    <strong>Country of Origin: </strong>
    <%= @movie.country_of_origin %>
  </dt>

  <dt>
    <strong>Duration in Minutes: </strong>
    <%= @movie.duration_in_minutes %>
  </dt>

  <dt>
    <strong>Director: </strong>
    <%= @movie.director.name %>
  </dt>

  <dt>
    <strong>Genre: </strong>
    <%= @movie.genre.name %>
  </dt>

  <dt>
    <strong>Release Status: </strong>
    <%= @movie.release_status.capitalize %>
  </dt>

  <dt>
    <%= button_to @movie.released? ? 'Set as Unreleased' : 'Set as Released', release_movie_path, {method: 'patch'} %>
  </dt>

  <dt>
    <strong>Publish Status: </strong>
    <%= @movie.publish_status.capitalize %>
  </dt>

  <dt>
    <%= button_to @movie.published? ? 'Set as Draft' : 'Set as Published', publish_movie_path, {method: 'patch'} %>
  </dt>
</dl>